<?xml version="1.0" encoding="utf-8"?>
<!-- $Revision$ -->
<!-- EN-Revision: 1f7a0e4af85d1b74595626afa1ca774c896e8388 Maintainer: mowangjuanzi Status: ready -->

<refentry xml:id="fiber.throw" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
 <refnamediv>
  <refname>Fiber::throw</refname>
  <refpurpose>恢复执行带有异常的 fiber</refpurpose>
 </refnamediv>

 <refsect1 role="description">
  &reftitle.description;
  <methodsynopsis>
   <modifier>public</modifier> <type>mixed</type><methodname>Fiber::throw</methodname>
   <methodparam><type>Throwable</type><parameter>exception</parameter></methodparam>
  </methodsynopsis>
  <para>
   通过从当前 <methodname>Fiber::suspend</methodname> 调用抛出的给定异常恢复 fiber。
  </para>
  <para>
   如果调用此方法时 fiber 未挂起，将抛出 <classname>FiberError</classname>。
  </para>
 </refsect1>

 <refsect1 role="parameters">
  &reftitle.parameters;
  <variablelist>
   <varlistentry>
    <term><parameter>exception</parameter></term>
    <listitem>
     <para>
      The exception to throw into the fiber from the current <methodname>Fiber::suspend</methodname> call.
     </para>
    </listitem>
   </varlistentry>
  </variablelist>
 </refsect1>

 <refsect1 role="returnvalues">
  &reftitle.returnvalues;
  <para>
   The value provided to the next call to <methodname>Fiber::suspend</methodname> or &null; if the fiber returns.
   如果 fiber 暂停前抛出一个异常，它将会从调用该方法时抛出。
  </para>
 </refsect1>

</refentry>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:t
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:1
sgml-indent-data:t
indent-tabs-mode:nil
sgml-parent-document:nil
sgml-default-dtd-file:"~/.phpdoc/manual.ced"
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
vim600: syn=xml fen fdm=syntax fdl=2 si
vim: et tw=78 syn=sgml
vi: ts=1 sw=1
-->
